### ISSUE TITLE
Undisclosed recipients ue is:open 

### ISSUE THREAD

**Issue by ApXaHgheJI** [swiftmailer/swiftmailer#964] opened 2017-06-30 11:25 UTC
Good day, when I try to set an Undisclosed recipients,
I receive an error : Address in mailbox given ["Undisclosed recipients"test@test.com] does not comply with RFC 2822, 3.6.2.

**Comment by Rotzbua** [comment] 2017-06-30 12:54
duplicate of  #382

**Closed** 2019-06-27 10:30 UTC
