### ISSUE TITLE
If sending fail, there is no info on WHY it's failed

### ISSUE THREAD

**Issue by realtebo** [swiftmailer/swiftmailer#353] opened 2013-08-08 12:54 UTC
mailer->send catch eventual exceptions:

```
catch (Swift_RfcComplianceException $e) 
```

and populate an array with failed recipients.

But how to determine WHY sending is failed ?!?!

**Comment by michaelhogg** [comment] 2015-01-23 15:50
Probably a duplicate of #164 and #424

**Closed** 2016-11-24 14:43 UTC
