### ISSUE TITLE
setBody() + addPart() with embedded images doesn't correctly add multipart/alternative entity

### ISSUE THREAD

**Issue by swiftmailer** [swiftmailer/swiftmailer#56] opened 2011-09-02 06:38 UTC
The following code:

@@@ php
<?php
require 'Swift-4.0.3/lib/swift_required.php';

//Messsage
$msg = Swift_Message::newInstance();
$msg -> setSubject('See my image');
$msg -> setFrom(array('swift@example.com'));
$msg -> setTo(array('thunderbird@example.com'=>'Thunderbird Client'));

$msg -> setBody("This is the plain text you'll see when I try and embed an image.");

//Image to embed
$cid = $msg->embed(Swift_Image::fromPath('logo.png'));
$img = '<p><img src="' . $cid . '" alt="Awesome Logo" width="120" height="36"></p>';

// HTML body
$msg -> addPart(
    "<h1>See my logo</h1>" .
    "<p>Outlook works, Thunderbird will fall back to plain text and show the " .
    "HTML body (as Part 1.2) and the image as attachments</p>" .
    $img,

```
'text/html'
```

);

//Transport and Mailer
$transport = Swift_MailTransport::newInstance();
$mailer = Swift_Mailer::newInstance($transport);

if($mailer->send($msg)) {
    echo "Message Sent";
}
@@@

Creates a structure similar to the following:

@@@
Content-Type: multipart/related; boundary="relbound"

--relbound
Content-Type: text/plain

Plain text here

--relbound
Content-Type: text/html

HTML here

--relbound
Content-Type: image/png

<png data here>

--relbound--
@@@

There should be a multipart/alternative entity wrapping this:

@@@
Content-Type: multipart/alternative; boundary="altbound"

--altbound
Content-Type: text/plain

Plain text here

--altbound
Content-Type: multipart/related; boundary="relbound"

--relbound
Content-Type: text/html

HTML here

--relbound
Content-Type: image/png

<png data here>

--relbound--

--altbound--
@@@

Probably a simple fix (I seem to remember fixing a similar bug which should have test coverage now).  Hopefully there's no conflict of logic between the two.

Original creation date: 2009-03-23T09:06:36Z
Original reporter: Ben
Original ticket: http://swiftmailer.lighthouseapp.com/projects/21527/tickets/77

**Comment by EdvinasBilius** [comment] 2016-12-02 07:47
It's almost 2017 and this bug still exist. 
Is there any possibility to fix it at last?

**Comment by mansoff** [comment] 2016-12-02 07:53
Doesn't work in 2016 ....
I can't use embedded images and plain text together ....

**Comment by TerjeBr** [comment] 2016-12-02 12:10
@EdvinasBilius and @mansoff  does it work with the workaround in #184 ?

May be this should be closed as a duplicate of #184?

**Comment by mansoff** [comment] 2016-12-02 12:18
@TerjeBr, no this is not working. Check in Thunderbird and use different text messages for HTML, PLAIN versions with embedded imges

**Comment by TerjeBr** [comment] 2016-12-02 17:25
Thunderbird has some known issues. Look at the email source, and see if the error is with thunderbird or the email that is being sent out.

**Comment by tadaszelvys** [comment] 2016-12-04 09:35
@TerjeBr it seems you're right, it is thunderbirds problem, other mail clients which can show plain text version of email (not source, but the actual message) works just fine.

**Comment by fabpot** [comment] 2019-03-02 10:27
I'm closing this issue as it's going to be fixed by Symfony Mailer/Mime, which will replace Swiftmailer eventually.

**Closed by fabpot** 2019-03-02 10:27 UTC
