### ISSUE TITLE
Address in mailbox given [tworzenieweb+hans.müller@gmail.com] does not comply with RFC 2822, 3.6.2.

### ISSUE THREAD

**Issue by tworzenieweb** [swiftmailer/swiftmailer#748] opened 2016-04-19 13:28 UTC
Hi,

i got the error like in subject for sending email to recipient contains special characters like ü.

``` php

    $message = Swift_Message::newInstance('some subject')
        ->setFrom('test@acme.com')
        ->setTo('tworzenieweb+hans.müller@gmail.com')
        ->setBody('test me');


    $result = $mailer->send($message);

```

Thanks

**Comment by GrahamCampbell** [comment] 2016-04-19 14:10
Why is this a bug? The email address is invalid.

**Comment by xdecock** [comment] 2016-04-19 14:24
not with utf-8 email address, but we welcome patches :)

On Tue, Apr 19, 2016 at 4:10 PM, Graham Campbell <notifications@github.com>
wrote:

> Why is this a bug? The email address is invalid.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/swiftmailer/swiftmailer/issues/748#issuecomment-211937200>
>



-- 
Xavier De Cock
GPG Fingerprint: 93CA EE3F 9F57 5BE1 AE4A  794D 3C74 CA9E E7A5 0C1B
GPG Id: 0xE7A50C1B

**Comment by tworzenieweb** [comment] 2016-04-19 14:27
Ok this is what I wanted to confront.

So is this format valid or no?

I read an RFC about it and it is pretty strict that this email address violates the rule but also there are some other validators like:

http://sphinx.mythic-beasts.com/~pdw/cgi-bin/emailvalidate

that said it is ok.

Also it is possible from gmail interface to send a valid email to this mailbox.

**Comment by madflow** [comment] 2016-04-28 08:14
@tworzenieweb As far as I know: https://tools.ietf.org/html/rfc2822 is obsoleted by https://tools.ietf.org/html/rfc5322, updated by https://tools.ietf.org/html/rfc5335, https://tools.ietf.org/html/rfc5336. Documented in #717 

@xdecock 

It is great to know that you do accept patches. At the moment this issue is the reason we consider maintaining a separate fork until this is resolved :S .

What is the favoured way to proceed? As far as I can see in the master branch there are some commits replacing the ```Grammar``` completely with a external script: https://github.com/egulias/EmailValidator.

* Would it be best to patch the current 5.4* release?
* Cherry-Pick/Integrate the commits from the master branch
* Wait for a 5.5 release?

Thanks

**Comment by cerlestes** [comment] 2016-06-06 10:22
Duplicate of #419

**Comment by adeslade** [comment] 2016-10-06 17:12
In 5.x could we do some version of the hack @e1himself provided in a gist (https://gist.github.com/e1himself/58c53aeef31a45345172), rather than pulling in version 2.0 of egulias/email-validator we could use version 1 which supports PHP 5.3. Would be happy to put this PR together.

There are a few issues related to this one floating around so it seems a common problem. For us it's critical and we'll probably fork temporarily in the mean time.

**Comment by xdecock** [comment] 2016-10-06 17:17
Maybe implement a specific email validator and provide it to change the di
map

**Comment by adeslade** [comment] 2016-10-06 17:29
Ah okay, that's probably better. I'll prepare a PR.

**Comment by adeslade** [comment] 2016-10-06 18:01
Did you mean something like this? https://github.com/adeslade/swiftmailer/commit/01cb0870d3514e83327f6a8936cc97cbe03abb4f. I'm happy to start a PR and fix the failing tests if you think it's on the right track.

**Comment by fabpot** [comment] 2016-11-13 15:39
fixed in master

**Closed by fabpot** 2016-11-13 15:39 UTC
