### ISSUE TITLE
Expected response code 250 but got code "235"

### ISSUE THREAD

**Issue by shkkmo** [swiftmailer/swiftmailer#669] opened 2015-09-29 20:15 UTC
I getting a periodic exception when sending mail via Mailgun:

Swift_TransportException: "Expected response code 250 but got code "235", with message "235 2.0.0 OK ""
from:
/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php line 383

Since it's periodic, I haven't yet figured out how to reproduce the Exception. I have checked the code and don't see anywhere that could possibly cause this exception unless Mailgun is returning the wrong response or there is an issue with the buffer sequence numbers.

https://github.com/swiftmailer/swiftmailer/search?utf8=%E2%9C%93&q=array%28250

Any thoughts on how I can narrow this down?

**Comment by xdecock** [comment] 2015-10-01 05:06
235 is sent after auth if i remember correctly do you use reset() ?  If so
it might be te place where a 235 might be sent

**Comment by alex198710** [comment] 2015-10-23 18:50
Hi. I ran into the same issue. Did you figure out how to get rid of this exception ? Thank you in advance.

**Comment by shkkmo** [comment] 2015-10-23 20:26
@alex198710 I haven't seen this reoccur yet, but we don't send THAT much mail. I've added http://swiftmailer.org/docs/plugins.html#logger-plugin so that if/when this exception is thrown, the SMTP transcript will be included in the exception message and we can get a better idea of why this is happening.

**Comment by alex198710** [comment] 2015-10-23 22:22
@shkkmo Me neither. I have no problem on my machine but when I'm on the server (ovh) I see this error... I catch the Swift_TransportException as a quick fix waiting for a true resolution...

**Comment by mmollick** [comment] 2016-02-23 14:25
Does anyone know anything more about this? I'm getting this message about 1-2 times daily since I switched my sender. Wondering if it's something I should be taking up with the sender...

**Comment by shkkmo** [comment] 2016-02-23 18:02
@mmollick I still haven't seen this re-occur on our servers. I did take it up with Mailgun and they couldn't provide any further information without the SMTP transcript. If you are reliably getting this error I would recommend setting up the logger plugin so that when you get this exception you also get the full SMTP transcript that lead to this error. Then when you do take this up with your mail sender, you can provide the exact behavior that is causing this error and can determine whose fault the error is.

**Comment by cawecoy** [comment] 2016-05-20 05:18
I am having the same issue,  periodic exception when sending mail via Mailgun. My error log:
```
Swift_TransportException: Expected response code 250 but got code "235", with message "235 2.0.0 OK
" in /vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:383
Stack trace:
#0 /vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(281): Swift_Transport_AbstractSmtpTransport->_assertResponseCode('235 2.0.0 OK\r\n', Array)
#1 /vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(243): Swift_Transport_AbstractSmtpTransport->executeCommand('RSET\r\n', Array, Array)
#2 /vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/Auth/LoginAuthenticator.php(46): Swift_Transport_EsmtpTransport->executeCommand('RSET\r\n', Array)
#3 /vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/AuthHandler.php(176): Swift_Transport_Esmtp_Auth_LoginAuthenticator->authenticate(Object(Swift_SmtpTransport), 'postmaster@innb...', '63qxo4abkpc4')
#4 /vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(307): Swift_Transport_Esmtp_AuthHandler->afterEhlo(Object(Swift_SmtpTransport))
#5 /vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(118): Swift_Transport_EsmtpTransport->_doHeloCommand()
#6 /vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start()
#7 /vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(307): Swift_Mailer->send(Object(Swift_Message), Array)
#8 /vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(134): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message))
```
Any idea why?

**Comment by cawecoy** [comment] 2016-05-20 05:19
I am having the same issue,  periodic exception when sending mail via Mailgun. My error log:
```
Swift_TransportException: Expected response code 250 but got code "235", with message "235 2.0.0 OK
" in /vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php:383
Stack trace:
#0 /vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(281): Swift_Transport_AbstractSmtpTransport->_assertResponseCode('235 2.0.0 OK\r\n', Array)
#1 /vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(243): Swift_Transport_AbstractSmtpTransport->executeCommand('RSET\r\n', Array, Array)
#2 /vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/Auth/LoginAuthenticator.php(46): Swift_Transport_EsmtpTransport->executeCommand('RSET\r\n', Array)
#3 /vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/AuthHandler.php(176): Swift_Transport_Esmtp_Auth_LoginAuthenticator->authenticate(Object(Swift_SmtpTransport), 'postmaster@innb...', '***')
#4 /vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/EsmtpTransport.php(307): Swift_Transport_Esmtp_AuthHandler->afterEhlo(Object(Swift_SmtpTransport))
#5 /vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php(118): Swift_Transport_EsmtpTransport->_doHeloCommand()
#6 /vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start()
#7 /vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(307): Swift_Mailer->send(Object(Swift_Message), Array)
#8 /vendor/laravel/framework/src/Illuminate/Mail/Mailer.php(134): Illuminate\Mail\Mailer->sendSwiftMessage(Object(Swift_Message))
```
Any idea why?

**Comment by shkkmo** [comment] 2016-05-23 19:58
@samvaughton @cawecoy If you want Mailgun to fix this, someone who can reliably reproduce this needs to enable the Swiftmailer Logger Plugin I mentioned above and get examples of the SMTP transcript.

something like this should work:

```
services:
    smtp.swiftmail.logger.array:
        class:      	Swift_Plugins_Loggers_ArrayLogger

    smtp.swiftmail.logging.plugin:
        class:      	Swift_Plugins_LoggerPlugin
        arguments: 
            logger: 	"@smtp.swiftmail.logger.array"
        tags:
           - { name: 	swiftmailer.instant_mailer.plugin }
           - { name: 	swiftmailer.spool_mailer.plugin }
```

Then you just need to catch the Swift_TransportException and call `$container->get('smtp.swiftmail.logger.array')->dump()` to get the transcript.

**Comment by samvaughton** [comment] 2016-05-23 22:13
In the end I changed to the Mailgun API as I didn't have time to debug (critical emails needed to go out). If one of the organizations has their custom SMTP credentials using Mailgun then I'll come back to this and investigate.

Thanks for providing this info though!

**Comment by cbloss** [comment] 2016-05-26 17:02
Hey @samvaughton , what did you change with the API settings? I'm currently getting the same issues. It just started this week and I haven't changed anything. I think I saw something on StackOverflow earlier this week that SMTP can't do TSL connections, but I can't find the thread.

**Comment by samvaughton** [comment] 2016-05-26 18:37
@cbloss I used their PHP Library:

```
$mg = new Mailgun($this->container->getParameter('mailgun.api_key'), new \Http\Adapter\Guzzle6\Client());
$domain = $this->container->getParameter('mailgun.domain');

$data = [
    'to' => $params['to'],
    'from' => $params['from'],
    'html' => $params['content'],
    'subject' => $params['subject'],
    'v:notificationId' => $notification->getId(),
];

// Redacted

$result = $mg->sendMessage($domain, $data);
```

mailgun/mailgun-php: 2.0
guzzlehttp/guzzle: 6.2.0
php-http/guzzle6-adapter: 1.1.1

Hope that helps.

**Comment by cbloss** [comment] 2016-05-26 18:54
Thanks @samvaughton! I'll have to check it out. I'm using Laravel 4.2 currently (with plans to switch to 5 of course). I'm hoping this will work still in my situation. THANKS!!!

**Comment by mmollick** [comment] 2016-05-26 20:35
I ended up switching to the mailgun API as well. @cbloss Laravel has a mailgun driver built right in.

**Comment by jad-bluemoon** [comment] 2016-06-02 16:07
FWIW, I was getting the same error (laravel->SwiftMailer->Mailgun).  I added the SwiftMailer Logger Plugin and saw the following transaction:
++ Starting Swift_SmtpTransport<br /> &lt;&lt; 220 ak47 ESMTP ready <br /> &gt;&gt; EHLO [127.0.0.1] <br /> &lt;&lt; 250-ak47 250-AUTH PLAIN LOGIN 250-SIZE 52428800 250-8BITMIME 250-ENHANCEDSTATUSCODES 250 STARTTLS <br /> &gt;&gt; STARTTLS <br /> &lt;&lt; 220 2.0.0 Start TLS <br /> &gt;&gt; EHLO [127.0.0.1] <br /> &lt;&lt; 250-ak47 250-AUTH PLAIN LOGIN 250-SIZE 52428800 250-8BITMIME 250-ENHANCEDSTATUSCODES <br /> &gt;&gt; AUTH LOGIN <br /> &lt;&lt; 334 {ID?} <br /> &gt;&gt; {KEY} <br /> &lt;&lt; 334 {PWD?} <br /> !! Connection to tcp://smtp.mailgun.org:587 Timed Out (code: 0)<br /> &gt;&gt; RSET <br /> &lt;&lt; 235 2.0.0 OK <br /> !! Expected response code 250 but got code &quot;235&quot;, with message &quot;235 2.0.0 OK &quot; (code: 235)<br /> [Swift_TransportException] Expected response code 250 but got code "235", with message "235 2.0.0 OK 

It looks like the final part of the AUTH LOGIN is being received by Mailgun, but the response isn't coming back quickly enough(?); whatever the reason, Swift_Transport is trying to reset the connection and expects a 250, but is getting the successful AUTH LOGIN response code (235 2.0.0 OK) from the previous message.

Partially related, I can't catch SwiftTransport_Exceptions.  I've read that the mail message is spooled so the error doesn't get thrown until the kernel exits, bypassing in-code exception handling.  I haven't found a good way to disable the queue in Laravel (lots of posts about disabling in Symphony)--I'm guessing that'll slow down front-end responsiveness as well.  If anyone has a tip, pass it on.

**Comment by mmollick** [comment] 2016-06-02 16:22
You can set Laravel's queue driver to `synchronous`. This should allow the queued items to be processed as they're called. Not sure if this clears up the issue of catching exceptions.

**Comment by cbloss** [comment] 2016-06-02 17:16
@mmollick I'll have to check that out. I only see smtp, mail or sendmail as the options. I wonder if 4.2 has it. 

I'm not using the Laravel's queue. I wonder if I did switch to using the queue if that will help as well.

**Comment by mmollick** [comment] 2016-06-04 16:00
@cbloss Ah I forgot laravel had a non queued mailer option, I would guess doing `Mail::send` would bypass the Laravel queue but I haven't looked at the source code for it.

**Comment by sanjitkung** [comment] 2019-12-18 02:06
is there any fix for this? I am using Laravel 5.8 and recently start getting the similar error.

```
Swift_TransportException: Failed to authenticate on SMTP server with username "SMTP_Injection" using 2 possible authenticators. Authenticator LOGIN returned Expected response code 250 but got code "235", with message "235 2.0.0 Authed. Go on.
". Authenticator PLAIN returned Expect
```

**Comment by liepumartins** [comment] 2020-04-17 12:54
Any updates?
Having this with Laravel 5.8 and 6.18

```
Failed to authenticate on SMTP server with username "noreply@example.com" using 2 possible authenticators. Authenticator LOGIN returned Expected response code 250 but got code "235", with message "235 2.7.0 Authentication successful

". Authenticator XOAUTH2 returned Expected response code 250 but got code "503", with message "503 5.5.2 Auth command already specified
". {"exception":"[object] (Swift_TransportException(code: 0): Failed to authenticate on SMTP server with username \"noreply@example.com\" using 2 possible authenticators. Authenticator LOGIN returned Expected response code 250 but got code \"235\", with message \"235 2.7.0 Authentication successful
\". Authenticator XOAUTH2 returned Expected response code 250 but got code \"503\", with message \"503 5.5.2 Auth command already specified
\". at /srv/app/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/AuthHandler.php:191)
```


Also occasional these:
```
fgets(): SSL: Connection reset by peer {"exception":"[object] (ErrorException(code: 0): fgets(): SSL: Connection reset by peer at /srv/app/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:162)
```

```
Failed to authenticate on SMTP server with username "noreply@example.com" using 2 possible authenticators. Authenticator LOGIN returned Connection to tcp://smtp-mail.outlook.com:587 Timed Out. Authenticator XOAUTH2 returned Connection to tcp://smtp-mail.outlook.com:587 Timed Out. {"exception":"[object] (Swift_TransportException(code: 0): Failed to authenticate on SMTP server with username \"noreply@example.com\" using 2 possible authenticators. Authenticator LOGIN returned Connection to tcp://smtp-mail.outlook.com:587 Timed Out. Authenticator XOAUTH2 returned Connection to tcp://smtp-mail.outlook.com:587 Timed Out. at /srv/app/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/Esmtp/AuthHandler.php:191) 
```

**Comment by bradleygreen** [comment] 2020-07-09 01:52
I have a production eCommerce environment using swiftmailer on Laravel 5.8 using smtp injection with sparkpost. We had this 235-expected-250 exception being thrown in laravel 4.2, and now again in 5.8. The app sends about 2000 emails a day and this error happens every week or so, but 6-30 times on the day it happens. This tells me that it's possibly traffic-related, or server related (our end or theirs). 

The message I'm getting is:
_Error : Failed to authenticate on SMTP server with username "SMTP_Injection" using 2 possible authenticators. Authenticator LOGIN returned Expected response code 250 but got code "235", with message "235 2.0.0 Authed. Go on. ". Authenticator PLAIN returned Expected response code 250 but got code "550", with message "550 5.0.0 Already authed. ". on line: 191_

I haven't found a good way to handle the exception, and also it's so irregular I haven't spent the time to figure out how to reproduce the error for testing solutions. 

In hopes we can establish a pattern, here are the dates I experienced this error (remember thousands of emails worked fine each of these days):
July 7, 2020 (1 time)
June 30 (7)
June 17 (12)
June 16 (24)
June 15 (24)
June 13 (1)
June 10 (2)
June 4 (1)
June 1 (1)
March 11 (1)
Feb 15 (3)
Dec 17, 2019 (7)
Dec 16 (4)
Dec 10 (2)
Oct 31 (1)
Oct 30 (3)

**Comment by nathan-c-jones** [comment] 2020-09-14 12:37
Has there been any update on this? Our application is running Laravel 5.5 and hasn't run into any issues until recently. We're seeing the same error message as bradleygreen.

We send around a dozen emails a day so there's less data to go off of, but we had emails fail on 9/9, 9/11, and 9/14. All other emails those days went out without issue.

**Closed** 2021-11-17 07:10 UTC
