### ISSUE TITLE
Trying to send email to recipient like "test..test@gmail.com" causes \Swift_RfcComplienceException.

### ISSUE THREAD

**Issue by ohmytribe** [swiftmailer/swiftmailer#411] opened 2013-12-31 03:02 UTC
Trying to send email to recipient that has a sequence of two or more dots in email address causes \Swift_RfcComplienceException.

``` php
$message = new \Swift_Message('test subject', 'test body');
$message->setTo('test..test@gmail.com');
$message->setFrom('example@example.com');
$mailer->send($message);
```

Despite this format really does not comply with RFC, this still can be a real email address that is supported by many email service providers (e.g. gmail). I think there should be at least some configuration parameter if to use strict RFC validation or not.

**Comment by BenMorel** [comment] 2017-02-11 15:05
Duplicate of #411

**Comment by BenMorel** [comment] 2017-02-11 15:23
I came across the same problem, too. The thing is, although there is a standard for email address formats, there is a competing, de-facto standard that's emerging with HTML5.

For example, Swift Mailer is refusing emails ending with a dot (`user.name.@gmail.com`), but in HTML5, an `email` input will accept this email. And it is worth noting that **this email address does work on Gmail**.

To quote the [HTML5 W3C recommendation](https://www.w3.org/TR/html5/forms.html#e-mail-state-(type=email)):

> This requirement is a willful violation of RFC 5322, which defines a syntax for e-mail addresses that is simultaneously too strict (before the "@" character), too vague (after the "@" character), and too lax (allowing comments, whitespace characters, and quoted strings in manners unfamiliar to most users) to be of practical use here.

> The following JavaScript- and Perl-compatible regular expression is an implementation of the above definition.

> /^[a-zA-Z0-9.!#$%&'*+/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/

As there are two competing definitions, I would suggest that Swift Mailer offers a user-configurable option to either:

- strictly validate email addresses based on RFC 2822 (the default)
- validate email addresses based on the W3C recommendation
- not validate email addresses (not sure about this one)

This would be backwards-compatible, and would open Swift Mailer to a wider range of use cases. In my case, I'm using HTML5 `email` inputs on the front-end, so I'm validating emails on the back-end with the same rules. I queue my emails for sending alright, and then my worker pool encounters a `Swift_RfcComplianceException`, and the email is never sent. Painful.

I'll be happy to submit a PR if lead developers are OK with the approach suggested above.

*Side note: [RFC 2822](https://tools.ietf.org/search/rfc2822) has been obsoleted by [RFC 5322](https://tools.ietf.org/search/rfc5322), it would be worth checking if the email address format has been updated there.*

**Comment by imclean557** [comment] 2019-04-09 06:37
> _Side note: [RFC 2822](https://tools.ietf.org/search/rfc2822) has been obsoleted by [RFC 5322](https://tools.ietf.org/search/rfc5322), it would be worth checking if the email address format has been updated there._

The format <name@example.com> is valid for a header field according to RFC 5322 but is failing swiftmailer's validation.

See: https://tools.ietf.org/html/rfc5322#section-3.4

**Comment by imclean557** [comment] 2019-04-09 23:18
It looks like Swift Mailer 6 uses `egulias/email-validator` which may resolve this issue.

**Closed** 2019-06-27 10:43 UTC

**Comment by imclean557** [comment] 2019-08-12 22:50
I haven't used Swift Mailer 6. Does it fix the validation errors with email addresses within angle brackets?

Has it removed the ability to set the "Return-Path" header directly?
