### ISSUE TITLE
Return path not working

### ISSUE THREAD

**Issue by alex0910** [swiftmailer/swiftmailer#690] opened 2015-11-14 11:03 UTC
Hi,

I set the return path to an ovh email address, and i never received delivery failure emails.
Here is my code : 

$message = Message::newInstance()
                ->setSubject($subject)
                ->setTo($to)
                ->setFrom(array(
                    $mailSettings->fromEmail => $mailSettings->fromName
                ))
                ->setSender($mailSettings->fromEmail)
                ->setReturnPath($mailSettings->fromEmail)
                ->setBody($template, 'text/html');

I really don't know why it's not working, is it a known issue ?

Thanks!

**Comment by PatchRanger** [comment] 2016-06-26 14:48
Possible duplicate of #384 .

**Comment by PatchRanger** [comment] 2016-06-29 15:02
Avoid using `Return-Path` header - it's SMTP-server job to determine which `Return-Path` to use. You should set `Sender` header with your bounce address instead. Refer to http://stackoverflow.com/a/26765956 for details.

**Closed** 2021-11-17 07:10 UTC
