### ISSUE TITLE
No Swift_TransportException raised on relay access denied (SMTP)

### ISSUE THREAD

**Issue by dazoot** [swiftmailer/swiftmailer#424] opened 2014-01-21 15:13 UTC
When sending mail via SMTP transport, normal behaviour would be if you encounter SMTP errors to raise the exception and let the developper catch it.

Swift silently drops the exceptions (including message) returning False when calling send(...).

method: _doMailTransaction in file AbstractSmtpTransport.php

```
        } catch (Swift_TransportException $e) {
            $failedRecipients[] = $forwardPath;
        }
```

(this is just one example)

**Comment by michaelhogg** [comment] 2015-01-23 15:51
Probably a duplicate of #164 and #353

**Comment by karpy47** [comment] 2016-09-17 10:45
+1
I would really like to see this resolved somehow. Getting info on why an address was rejected is important. For me it's typically because I hit a sending limit with my mail provider.
Re-throwing the exception would probably make older implementations break, since they do not check for that exception. Why not just add an error-method containing the last error?

**Closed** 2021-11-17 07:10 UTC
