### ISSUE TITLE
FatalThrowableError in EsmtpTransport.php line 55: Type error: Argument 1 passed to Swift_Transport_EsmtpTransport::__construct() must implement interface Swift_Transport_IoBuffer, none given, called in /var/www/gosoug/vendor/swiftmailer/swiftmailer/lib/classes/Swift/SmtpTransport.php on line 37

### ISSUE THREAD

**Issue by dhineshdhiran** [swiftmailer/swiftmailer#905] opened 2017-04-21 05:49 UTC
Swiftmailer not working after fresh installed laravel 5.4 
OS : ubuntu 17.04
PHP Version : 7.0.1
Swiftmailer : 5.4
![screenshot from 2017-04-21 14-44-36](https://cloud.githubusercontent.com/assets/27845247/25271240/1736ba92-26a1-11e7-982e-976af719a84a.png)

**Comment by Rotzbua** [comment] 2017-04-21 08:29
Wow, what a bad issue report. Should we guess your system/server? operation system? php version? swiftmailer version?

**Comment by amenk** [comment] 2017-05-05 10:26
Looks like laravel? Can you reproduce the issuse in a clean laravel setup with your config? What is your configuration?

**Comment by fabpot** [comment] 2017-05-15 19:21
Closing as there is no answers from the reporter.

**Closed by fabpot** 2017-05-15 19:21 UTC

**Comment by sarelvdm** [comment] 2017-06-06 09:35
Im also getting this error. Using Swiftmailer of Slim3.

**Comment by cioddi** [comment] 2017-09-20 14:39
This error is not related to PHP versions or different Swift versions as some people may assume.

The problem most likely is that the file swift_init.php was not loaded correctly. So if you are using composer run "composer dump-autoload" once that should resole the problem. If you are doing something hacky make sure to require_once the file swift_init.php

That way the dependency maps will be populated and everything should run fine.
