### ISSUE TITLE
Broken pipe in StreamBuffer.php on line 236

### ISSUE THREAD

**Issue by juanmaia** [swiftmailer/swiftmailer#490] opened 2014-06-03 22:28 UTC
Hey guys, does anyone possibly know what could be causing this issue to happen?

```
PHP Notice:  fwrite(): send of 41 bytes failed with errno=32 Broken pipe in /var/www/ACME/releases/20140602200156/vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php on line 236
```

I'm sending the email from a worker (gearman message queue, daemonized by supervisord) and I'm using Symfony ~2.4, swiftmailer-bundle ~2.3 (swiftmailer 5.1). 

When I restart the worker from supervisorctl the email is sent.

I appreciate any help. Thanks.

**Comment by vincentpazeller** [comment] 2015-01-30 20:29
I am also having this issue... no fix? I think this is a real problem that should be fixed since this is common to have batches sending emails, no?

**Comment by xdecock** [comment] 2015-01-31 06:57
This is your smtp server dropping the connection.

Or a network error, i'm pretty sure it's quite hard to fix from here, but
i'll be glad to review patches.
Le 30 janv. 2015 21:29, "vincentpazeller" <notifications@github.com> a
écrit :

**Comment by vincentpazeller** [comment] 2015-01-31 09:53
Actually, the server is gmail... so thats a bit uncomfortable, but I am using sc0rp10's workaround which seems to work well :)

**Comment by maxbanton** [comment] 2015-02-02 13:15
Same problem with Laravel daemon and Yandex SMTP

**Comment by xdecock** [comment] 2015-02-02 14:15
Yes, it closes the connection, wait 5 seconds and retry, it shouldn't be hardcoded at library level, but handled on application level.

**Comment by vincentpazeller** [comment] 2015-02-02 14:36
What I am not sure is if it is right from swiftmailer's point of view to keep connections open for minutes (because, that's what's happening if my understanding is good)... I mean couldn't/shouldn't swiftmailer close unused connection's after a while? Is this normal that a script that don't send emails for minutes keeps connections open? Couldn't connections be re-open "on-demand"? In my opinion, this behavior is weird for long running process and could/should be handled at the library level (you might add a "connection_timeout" parameter and set it by default to the infinite since this is not the most common case...).

**Comment by xdecock** [comment] 2015-02-02 14:54
I'm not sure you understand how php work.

It's a single thread, single flow process, as such, while your code is waiting for an answer from your database to send your next email, we can't possibly as a library decide to close a connection because you won't use it.

See Swiftmailer as a toolbox, if you take the hammer and leave it on the table it won't get back in the toolbox by itself.

**Comment by YOzaz** [comment] 2015-02-02 15:18
@xdecock you're not 100% right. mysqli_close(), fclose(), exit(), socket_close() functions are recommended once library or script finishes it's job. I think the problem is in library architecture, where - from my understanding - it's not quite clear to identify when the job is actualy finished (but you can always assume that at some point).

**Comment by xdecock** [comment] 2015-02-02 15:26
@Yozaz, connection will be closed if you free the objects.

The hard part being : i've just finished sending one mail, will the php code i'm working for ask me to do some more job, or is it done? (i need to take the decision before yielding execution).

Next time I'll be able to clean up things is the next-time the user ask me to do something, it might take a while.

PS : can you provided me the location of the recommendation you talk about?

**Comment by YOzaz** [comment] 2015-02-02 16:11
@xdecock maybe it will sound crazy, but how about in send() function itself, at the end of it? With additional flag, e.g.? Or through different method? Will look great:
```php
Swift_Mailer::newInstance($transport)->send( $message, $recipients, false );
// or even further :)
Swift_Mailer::open('smtp')->send($message)->close();
```

**Comment by xdecock** [comment] 2015-02-02 16:14
you can allready close after you're done, i'm working with long working
process and handle this on the process level (some of them working without
error, without failing for month).

add $transport->stop(); and, it's clean.

You're welcome :)



On Mon, Feb 2, 2015 at 5:11 PM, Marijus Plančiūnas <notifications@github.com
> wrote:

> @xdecock <https://github.com/xdecock> maybe it will sound crazy, but how
> about in send() function itself, at the end of it? With additional flag,
> e.g.? Or through different method? Will look great:
>
> Swift_Mailer::newInstance($transport)->send( $message, $recipients, false );// or even further :)Swift_Mailer::open('smtp')->send($message)->close();
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swiftmailer/swiftmailer/issues/490#issuecomment-72483652>
> .
>



-- 
Xavier De Cock
GPG Fingerprint: 93CA EE3F 9F57 5BE1 AE4A  794D 3C74 CA9E E7A5 0C1B
GPG Id: 0xE7A50C1B

**Comment by YOzaz** [comment] 2015-02-02 16:18
@xdecock I understand what you're doing, but was rather pointing to a class implementation where auto-start is implemeneted:
```php
if (!$this->_transport->isStarted()) {
   $this->_transport->start();
}
```
... while auto-stop (or autoclose) - does not. This, in my eyes, breaks the long term process.
But you're right, maybe we need just to address Symfony/Laravel developers to start and close transport - or let's say in reality, connection with SMTP manualy for every mail.

**Comment by sc0rp10** [comment] 2015-02-02 16:40
@xdecock I see problem in out of sync internal resources: 
`$this->_transport->isStarted()` returns true, but socket isn't still open and send fails. Maybe need check their state in `send` and reopen socket if this is closed?

**Comment by xdecock** [comment] 2015-02-02 16:55
yes, However, auto-start might be an error, as autostopping might trigger
more error (lots of fai have limits on connections / period).

For the isStarted(); the answer true is ok,

Here is my fail-safe restart before email TXN (might be useful for other,
and no magic, just following smtp standard)


try {
if ($this->swift_transport instanceof Swift_Transport_AbstractSmtpTransport
){
$this->swift_transport->reset(); // Send RSET to restart the smtp status
}
} catch ( Exception $e ) {
$this->log('[LOOP] Got Exception while resetting transport');
try {
$this->swift_transport->stop (); // Stop (QUIT, will probably fail too)
} catch ( Exception $e ) {
$this->log('[LOOP] Got Exception while stopping transport');
}
$this->swift_transport->start (); // Start Back
}



On Mon, Feb 2, 2015 at 5:40 PM, Konstantin Zamyakin <
notifications@github.com> wrote:

> @xdecock <https://github.com/xdecock> I see problem in out of sync
> internal resources:
> $this->_transport->isStarted() returns true, but socket isn't still open
> and send fails. Maybe need check their state in send and reopen socket if
> this is closed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swiftmailer/swiftmailer/issues/490#issuecomment-72489351>
> .
>



-- 
Xavier De Cock
GPG Fingerprint: 93CA EE3F 9F57 5BE1 AE4A  794D 3C74 CA9E E7A5 0C1B
GPG Id: 0xE7A50C1B

**Comment by vincentpazeller** [comment] 2015-02-02 22:53
I agree with Marijus. It is weird to have auto-start and not auto-close...
while this scheme is working well for short running processes, it is not
good for long running processes. I believe developers should never be
surprised by the behavior of a library. I think that if you can only
achieve half-magic (auto-start but no auto-close), this might be evil. Why
not expose 2 behaviors (thats pseudo-code):

1) $mailer->send( $message); // auto open + auto close connection
immediately after message has been sent. No reuse of connection. That for
the single message use case

2) $mailer->startBatch(); //explicitely open connection
    $mailer->send($message1) ; $mailer->send($message2); etc. //send as
many messages and reuse connection
    $mailer->endBatch(); //explicitely close connection

Those behaviors are similar to how dbms work (auto-commit vs transactions).
No magic...


Regards

Vincent


PS: I think I have a pretty good understanding of php

On Mon, Feb 2, 2015 at 5:18 PM, Marijus Plančiūnas <notifications@github.com

**Comment by xdecock** [comment] 2015-02-03 04:49
This will be a huge api break, won't be done on a 5.x so if needs to be
fixed for laravel / symfony, should be done in the bundle
Le 2 févr. 2015 23:53, "vincentpazeller" <notifications@github.com> a écrit
:

**Comment by hugoeld** [comment] 2015-03-13 11:37
+1

**Comment by MathieuDoyon** [comment] 2015-03-25 01:58
Same problem with Laravel 5, mandril smtp, Mail::queue through amazon sqs queue driver

**Comment by gaaarfild** [comment] 2015-03-30 09:12
So, from what side it has to be fixed? Laravel or Swiftmailer?
This is serious problem for customers, who doesn't receive emails.
P.S.: Laravel 5.

**Comment by YOzaz** [comment] 2015-03-30 09:21
@gaaarfild it's complicated. SwiftMailer authors say their library doesn't support long-term executions (doh!). Laravel authors say "make a PR to fix this": https://github.com/laravel/framework/issues/4573. Any volunteers? :)

**Comment by wyred** [comment] 2015-03-30 09:22
@gaaarfild Just don't run your queue tasks in daemon mode.

**Comment by YOzaz** [comment] 2015-03-30 09:33
@wyred do you mean running as Queue listener (instead of deamon) for specific Beanstalkd tube? http://laravel.com/docs/4.2/queues#running-the-queue-listener

**Comment by gaaarfild** [comment] 2015-03-30 09:33
@YOzaz I would be happy if I at leas know where to do it :)
@wyred How I have to run it? Using supervisor.

**Comment by wyred** [comment] 2015-03-30 09:40
Yes, just change your supervisor configuration from queue:work to queue:listen. Or you can experiment with using queue:work but without the --daemon option

**Comment by xdecock** [comment] 2015-03-30 09:40
The issue here is : The server you're connected too has closed the
connection, it can happen because you slept with your connection open or
because you sent too many mails or spam or because the server has been
rebooted / restarted / crashed, ... We're on the internet (or something
close to it), bad things happen all the time, Swiftmailer is a library
handling :

* Message Composition
* Mail Transport Layer (SMTP / sendmail / mail())

The goal of this transport layer is to transmit the mail, not to hide
everything that might happen.

It should be fixed in laravel (if connection being closed is seen as a
minor glitch)

To be honest, connection being closed has to be expected, and is bound to
happen over long term.

However, if swiftmailer, reopen the connection magically, a user might miss
information (the server starting to refuse the mails, ...)

Furthermore, i think the course of action is more of reducing the number of
"magic code" in the library instead of adding some, magic code, reduces
transparency, and usually triggers edge case behaviour

I hope this answer is complete enough and can close this ongoing discussion.

On Mon, Mar 30, 2015 at 11:22 AM, Erik Yeoh <notifications@github.com>
wrote:

> @gaaarfild <https://github.com/gaaarfild> Just don't run your queue tasks
> in daemon mode.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swiftmailer/swiftmailer/issues/490#issuecomment-87607892>
> .
>



-- 
Xavier De Cock
GPG Fingerprint: 93CA EE3F 9F57 5BE1 AE4A  794D 3C74 CA9E E7A5 0C1B
GPG Id: 0xE7A50C1B

**Comment by YOzaz** [comment] 2015-03-30 09:58
@xdecock you're absolutely right. But you know - it's a strange fact that Laravel ships with SwiftMailer package as a default, while it's not working properly in big applications (where mail queues are pretty much normal)...
I understand that this needs to be "fixed" in Laravel, or even requires a separate layer in between these two packages. However, it would be great having SwiftMailer magicaly changing it's behaviour in case it's used in most popular Framework in these days - like other packages do (Sentry, Beanstalkd, etc.). It can even go through separate file - connector / Service Provider, and you can expand them even further by having separate files for major frameworks out there.

**Comment by xdecock** [comment] 2015-03-30 10:05
See my comment from 2 February, it's something around 10 lines of code on the "application side" it will be way worse on the library side, you can create a pull request with my code without issue, if it can solve the issue

**Comment by YOzaz** [comment] 2015-03-30 10:11
Hrrrr allllright. I'll make a PR for Laravel...

**Comment by gaaarfild** [comment] 2015-03-30 10:22
@YOzaz You're awesome!

**Comment by YOzaz** [comment] 2015-03-30 10:29
Quick question:
```php
if ( $this->swift_transport instanceof Swift_Transport_AbstractSmtpTransport...
```
is this one required?

**Comment by xdecock** [comment] 2015-03-30 10:57
no, more of a way to do a late instanciation in my own code, (instanciate
the transport as late as possible) but, it can be done on class
instanciation

On Mon, Mar 30, 2015 at 12:29 PM, Marijus Plančiūnas <
notifications@github.com> wrote:

> Quick question:
>
> if ( $this->swift_transport instanceof Swift_Transport_AbstractSmtpTransport...
>
> is this one required?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swiftmailer/swiftmailer/issues/490#issuecomment-87627949>
> .
>



-- 
Xavier De Cock
GPG Fingerprint: 93CA EE3F 9F57 5BE1 AE4A  794D 3C74 CA9E E7A5 0C1B
GPG Id: 0xE7A50C1B

**Comment by YOzaz** [comment] 2015-03-30 11:04
@xdecock can you take a look at my PR? https://github.com/laravel/framework/pull/8221

**Comment by xdecock** [comment] 2015-03-30 11:11
Seems not working ;)

The idea is : 

try Reset(); if OK (no exception) => transport is ready to run
if exception => Try stop (close connection)
try start

```php
try {
  if ($this->swift_transport instanceof Swift_Transport_AbstractSmtpTransport) {
    $this->swift_transport->reset(); // Send RSET to restart the smtp status
  }
} catch ( Exception $e ) {
  $this->log('[LOOP] Got Exception while resetting transport');
  try {
    $this->swift_transport->stop (); // Stop (QUIT, will probably fail too)
  } catch ( Exception $e ) {
    $this->log('[LOOP] Got Exception while stopping transport');
  }
  $this->swift_transport->start (); // Start Back
}
```

PS : the exceptions should be more specific for a pull request, but the idea is there if reset is succesful, then the connection is probably ok for a transaction (it can still fail for a lot of reasons while the mail is sent)

Your code does a close / open in any case

**Comment by YOzaz** [comment] 2015-03-30 11:14
Is there a way I can detect if connection is open?

**Comment by YOzaz** [comment] 2015-03-30 11:22
All done. https://github.com/laravel/framework/pull/8221

**Comment by xdecock** [comment] 2015-03-30 11:24
isStarted() will return true if the connection has been opened in the past,
but won't work if the server sent a RST TCP packet ("Broken Pipe") ;)

The reset() method sends the smtp RSET command which change the state of
the connection to "just after the EHLO response", + it does a write, so
will be it with the "Broken Pipe" Issue if the connection has been closed
by the server

On Mon, Mar 30, 2015 at 1:14 PM, Marijus Plančiūnas <
notifications@github.com> wrote:

> Is there a way I can detect if connection is open?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swiftmailer/swiftmailer/issues/490#issuecomment-87637466>
> .
>



-- 
Xavier De Cock
GPG Fingerprint: 93CA EE3F 9F57 5BE1 AE4A  794D 3C74 CA9E E7A5 0C1B
GPG Id: 0xE7A50C1B

**Comment by YOzaz** [comment] 2015-03-30 12:23
Great! Made 2 PRs for different versions:
5.0: https://github.com/laravel/framework/pull/8222
4.2: https://github.com/laravel/framework/pull/8225
Somebody was mentioning somewhere, that problem exists in Symfony as well?

**Comment by YOzaz** [comment] 2015-03-30 13:47
So, just to note - 4.2 is not supported, and this fix probably won't be pushed ("perhapse we can reconsider").
I'm starting to regret I spent my time here at all.

**Comment by YOzaz** [comment] 2015-03-30 14:06
@xdecock as Laravel authors don't want this PR, should I:
a) write a plugin for your library;
b) create a package for Laravel + SwiftMailer integration?

**Comment by xdecock** [comment] 2015-03-30 14:17
Not sure where we can implement the plugin, I'll need to check which events
exists

On Mon, Mar 30, 2015 at 4:06 PM, Marijus Plančiūnas <
notifications@github.com> wrote:

> @xdecock <https://github.com/xdecock> as Laravel authors don't want this
> PR, should I:
> a) write a plugin for your library;
> b) create a package for Laravel + SwiftMailer integration?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swiftmailer/swiftmailer/issues/490#issuecomment-87692055>
> .
>



-- 
Xavier De Cock
GPG Fingerprint: 93CA EE3F 9F57 5BE1 AE4A  794D 3C74 CA9E E7A5 0C1B
GPG Id: 0xE7A50C1B

**Comment by YOzaz** [comment] 2015-03-30 14:19
Actualy, don't bother - I would have to create package for registering plugin anyway.
Thanks.

**Comment by YOzaz** [comment] 2015-03-30 18:46
And here it is:
https://github.com/YOzaz/Laravel-SwiftMailer
Feel free to test it.

**Comment by gaaarfild** [comment] 2015-03-31 08:16
@YOzaz Tank you very much.
And for Laravel 5 are there some solutions?

**Comment by xdecock** [comment] 2015-03-31 08:17
He did this pull request :

https://github.com/laravel/framework/pull/8222

On Tue, Mar 31, 2015 at 10:16 AM, Dinar Garipov <notifications@github.com>
wrote:

> @YOzaz <https://github.com/YOzaz> Tank you very much.
> And for Laravel 5 are there some solutions?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swiftmailer/swiftmailer/issues/490#issuecomment-87991450>
> .
>



-- 
Xavier De Cock
GPG Fingerprint: 93CA EE3F 9F57 5BE1 AE4A  794D 3C74 CA9E E7A5 0C1B
GPG Id: 0xE7A50C1B

**Comment by YOzaz** [comment] 2015-03-31 08:43
@xdecock PR won't go through now.
@gaaarfild Mailer class should stay the same, only service provider needs to be different. I'll try to make separate branch for Laravel5 today if I'll be able to.

**Comment by gaaarfild** [comment] 2015-03-31 08:49
@YOzaz I have this issue even if not using queue.
```
production.ERROR: exception 'ErrorException' with message 'fwrite(): SSL operation failed with code 1. OpenSSL Error messages:
error:1409F07F:SSL routines:SSL3_WRITE_PENDING:bad write retry' in .../vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/StreamBuffer.php:232
```

**Comment by YOzaz** [comment] 2015-03-31 08:55
@gaaarfild not sure if my package will fix this - but we can try. @xdecock is a master about SMTP/SSL stuff here ;)

**Comment by YOzaz** [comment] 2015-03-31 11:51
Updated for Laravel 5 support: https://github.com/YOzaz/Laravel-SwiftMailer
Use version 3.

**Comment by mickeyfmann** [comment] 2015-03-31 14:45
I'm getting an error when trying to use the updated version in Laravel 5:

BadMethodCallException in ServiceProvider.php line 226:
Call to undefined method [package]

I remember seeing this a lot when Laravel 5 was still in development, I think its related to them pulling Workbench out of the core. Is it a matter of adding something else?

**Comment by YOzaz** [comment] 2015-03-31 15:10
@mickeyfmann try to use v3.1. It's a common Laravel 4 package porting to Laravel 5 problem.
Fixed with: https://github.com/YOzaz/Laravel-SwiftMailer/commit/34a45d4641f119921e49755b373c16e52e732534

**Comment by mickeyfmann** [comment] 2015-03-31 15:24
Yeah thats the version I installed. It seems to be related to how you're using the version_compare call to execute that package call. For example if I use '5.0' rather than '5.0.0' it runs without issue.

**Comment by YOzaz** [comment] 2015-03-31 15:44
OK, fixed - bumped to v3.1.1.
https://github.com/YOzaz/Laravel-SwiftMailer/commit/0b9c4aeeff5dae2701977f988a68023c7802552c

**Comment by YOzaz** [comment] 2015-09-03 09:03
@xdecock hi, how are you?
Guys are saying, that transport reset doesn't work in some cases. That's what they're getting:
```
fwrite(): SSL operation failed with code 1. OpenSSL Error messages: error:1409F07F:SSL routines:SSL3_WRITE_PENDING:bad write retry
```
See [here](https://github.com/YOzaz/Laravel-SwiftMailer/issues/1).
Any ideas? :smile:

**Comment by xdecock** [comment] 2015-09-03 09:07
allready replied there, i suspect a key renegotiation, but from what i see, on some cases we should not take into account the return value of the fwrite and resubmit the value as is, this will be a mess if it occurs to be the case :(

**Comment by garygreen** [comment] 2015-09-25 09:29
@xdecock any news on this? I would like to use Laravel in daemon mode but it seems swiftmailer wasn't really built with this in mind, so when connections are dropped / timed out from SMTP server swiftmailer breaks with a "fwrite() send broken pipe" error.

> Daemon workers are long running PHP processes, which can have side effects from code that wasn't built with that in mind.

> It looks like SwiftMailer isn't built to be run long-term. To have a guess, it looks like it might not be catering for the fact the connection can drop and errors out.

> There's nothing Laravel can do about it.

**Comment by michaelachrisco** [comment] 2015-11-09 17:45
Same issue as above. I am using Mail::send to send the email. It seems to only occur after long standing instances of php. Email still works but this error pops up after any emails were sent.

**Comment by diogotozzi** [comment] 2015-11-24 23:06
Same issue as above.

**Comment by juanmaia** [comment] 2015-11-24 23:15
boa @diogotozzi dando +1 no erro que abri, thanks man!

**Comment by ignatenkovnikita** [comment] 2015-12-22 16:58
I have error with running beanstalk server +  yii2 worker app.
And email was send, before time 5 minut i try send emailm and get error with "Error: timeout exceeded
" from postfix.
Dump analyze from mail server show, what app not send  command "QUIT". and postfix send "timeout".
After app not create new instace and send in broken instance and get error "fwrite(): send of 90 bytes failed with errno=32 Broken pipe".

I try close connection add afterAction "Yii::$app->mailer->getTransport()->stop();".

**Comment by ostretsov** [comment] 2016-01-04 05:20
Same issue but with dockerized consumer (RabbitMQ) based on swiftmailer and postfix on host machine. `$mailer->getTransport()->stop();` works well. Many thanks to @ramondelafuente for the right suggestion.

**Comment by YOzaz** [comment] 2016-04-07 15:30
@xdecock I think you can close this. Laravel 5 has a patch applied here: https://github.com/laravel/framework/commit/af8eb1face000f82e5c85e6eb822075fc313cbb9. For Laravel 4, people can use my package. For Symfony - I suppose it goes out of SwiftMailer scope anyway.
As per later bug - I'm like 99% sure it's about SSL certificate validity in server itself.

**Comment by danlake** [comment] 2016-04-20 11:23
@YOzaz Any thoughts on why I am getting the exact issue with a deamonized queue in Laravel 5 (I have checked the fix in [af8eb1f](https://github.com/laravel/framework/commit/af8eb1face000f82e5c85e6eb822075fc313cbb9) is in my code base)? My issue specifically is giving 3 lots of the following error:

`exception 'ErrorException' with message 'fwrite(): send of X bytes failed with errno=10053 An established connection was aborted by the software in your host machine.`

**Comment by YOzaz** [comment] 2016-04-20 14:08
@danlake it looks like Laravel 5 fix is not working. See my comment here: https://github.com/laravel/framework/issues/4573#issuecomment-211996632
I suppose `stop` doesn't close the connection.
You can still try using my package, I've just upgraded it: https://github.com/YOzaz/Laravel-SwiftMailer

**Comment by danlake** [comment] 2016-04-20 14:15
@YOzaz Great, a patch that didn't patch! I'll take a look at your package

**Comment by danlake** [comment] 2016-05-18 13:28
@YOzaz Apologies for the delay in responding but your package didn't address my specific issue, although logic dictates it should have. I have been through line by line and the SMTP server (Exchange) rejects the connection when deamonized.

**Comment by YOzaz** [comment] 2016-05-18 13:53
@danlake there's a PR for 5.1 at the moment here: https://github.com/laravel/framework/pull/13583 - which closes the connection after sending, not before it.

**Comment by cubiclesoft** [comment] 2016-06-04 14:50
I just ran into the `error:1409F07F:SSL routines:SSL3_WRITE_PENDING:bad write retry` message with the [Ultimate Web Scraper Toolkit](https://github.com/cubiclesoft/ultimate-web-scraper/), subsequently traced it back to a bad assumption about the SSL_write() call in PHP itself, and opened [issue 72333 on bugs.php.net](https://bugs.php.net/bug.php?id=72333).

The problem is a combination of non-blocking mode with SSL sockets when calling SSL_write() with different pointers in 'ext\openssl\xp_ssl.c' (if you've never cracked open the actual source code to PHP, this is a great opportunity to start doing so - otherwise, the bug report will be rather nonsensical).  I can't find a version of PHP without the bug, which means it has always been there but few people are trying to send large amounts of data at high enough rates on non-blocking SSL sockets to encounter it.  There is also no workaround in PHP userland except to temporarily disable non-blocking mode on a socket when writing data to a SSL-enabled socket, which may or may not be a showstopper (it is for me).  You can't easily detect the failure until it is far too late and PHP spits out that message.  Fixing PHP core is the only real solution.

**Comment by Jekis** [comment] 2017-01-27 16:11
When pipe is broken $mailer->getTransport()->stop() will fail as well. And due to this error transport cannot be stopped. The workaround is

```
// Let's try to send an email.
$tries = 3;
while ($tries--) {
    try {
        $sent = $this->mailer->send($message);
        break;
    } catch (\Exception $e) {
        // Connection problems
        // @see https://github.com/swiftmailer/swiftmailer/issues/490
        try {
            // Try to stop
            $this->mailer->getTransport()->stop();
        } catch (\Exception $e) {
            // Got Exception while stopping transport.
            // We have to set _started to 'false' manually, because due to an exception it is 'true' now.
            $t = $this->mailer->getTransport();
            $reflection = new \ReflectionClass($t);
            $prop = $reflection->getProperty('_started');
            $prop->setAccessible(true);
            $prop->setValue($t, false);
            $prop->setAccessible(false);
        }
    }
}
```

**Comment by YOzaz** [comment] 2017-01-27 16:48
@Jekis what's the reason behind 3 tries?

**Comment by Jekis** [comment] 2017-01-28 05:39
@YOzaz, it's specific for my project. The main part of my snippet is to execute stop() method inside try catch. I have a worker script that must send emails and I want to be sure email is sent. In your PRs you should use 2 tries. First could fail with broken pipe error and second will send it.

**Comment by spronkey** [comment] 2018-02-02 11:44
At the very least here I think the library should be trying to catch the error and convert it into some kind of Swift_ Exception, so that it's possible for consumers of the library to handle it without resorting to catch(\Exception $e).

As it stands right now the workarounds can break other code - like tests using mocks of swift.

**Comment by bwowk** [comment] 2018-04-27 13:13
FYI, I believe this is the correct solution:
```
#Swift_Transport
/**
     * Check if this Transport mechanism is alive.
     *
     * If a Transport mechanism session is no longer functional, the method
     * returns FALSE. It is the responsibility of the developer to handle this
     * case and restart the Transport mechanism manually.
     *
     * @example
     *
     *   if (!$transport->ping()) {
     *      $transport->stop();
     *      $transport->start();
     *   }
     *
     * The Transport mechanism will be started, if it is not already.
     *
     * It is undefined if the Transport mechanism attempts to restart as long as
     * the return value reflects whether the mechanism is now functional.
     *
     * @return bool TRUE if the transport is alive
     */
    public function ping();
```

**Closed** 2019-06-27 10:40 UTC

**Comment by alexislefebvre** [comment] 2021-05-24 10:32
I had the same issue while using `smtp.office365.com`, I fixed that issue by adding `encryption: tls` to the configuration of Swiftmailer.

**Comment by ytsurk** [comment] 2021-09-30 13:22
For me this issue:

`Broken pipe in Swift_Transport_StreamBuffer->doCommit() `

was caused by a faulty in-existant MTA-Path from an imported database ;)
