### ISSUE TITLE
Encoding is not applied to content added via $message->addPart()

### ISSUE THREAD

**Issue by mdiniz** [swiftmailer/swiftmailer#500] opened 2014-07-02 02:10 UTC
I'm sending a message with HTML and plain text content, and I would like to use 8bit encoding instead of quoted printable, so I do:

`$message->setEncoder(Swift_Encoding::get8BitEncoding())`

Later on I set the content:

```
$message->setBody('<span>hello</span>', 'text/html');
$message->addPart('hello', 'text/plain');
```

The email sent has the HTML part encoded as 8bit but the plain text part is still encoded as quoted printable. If I set the body with the plain text content and the HTML as a part, then only the text part is 8bit encoded.

That means, the encoding set in the message only applies to the body, not to the parts. I would expect it to apply to both of them.

I'm using Swift-5.2.1 from composer.

EDIT: this seems to be a rather old bug: https://github.com/swiftmailer/swiftmailer/issues/69
The problem didn't happen in version 3.3.2, but it happens in version 4 and 5

**Comment by fabpot** [comment] 2017-02-28 04:33
Closing as a duplicate of #69

**Closed by fabpot** 2017-02-28 04:33 UTC
