### ISSUE TITLE
Allowing non-ASCII characters in email addresses (aka RFC 6532 support)

### ISSUE THREAD

**Issue by jamesggordon** [swiftmailer/swiftmailer#898] opened 2017-04-04 03:56 UTC
I received a Swift_RfcComplianceException when trying to send an email that contained a 'u' with an umlaut in the local part of the email address (eg. "müller@example.com").

Currently, SwiftMailer officially supports RFC 2822, which only provides for ASCII characters in the local part of the email address. Are there any plans to add support for RFC 6532? This would allow non-ASCII characters to be used in both the local-parts and domain of an email address.

**Comment by jamesggordon** [comment] 2017-05-16 04:00
I was just hunting around the code in preparation for making the necessary changes myself when I discovered that there is a major upgrade in the works (v6 on the master branch) that resolves this issue. The new version ditches a lot of the pre-existing Mime code and utilises another library for email address validation, which works with UTF8 characters. The only catch is that v6 will not work with PHP versions < 7.0.

**Comment by fabpot** [comment] 2017-05-19 16:05
Closing as this is indeed something part of the upcoming version 6.

**Closed by fabpot** 2017-05-19 16:05 UTC

**Comment by PierreRambaud** [comment] 2018-05-28 12:49
Is there a possibility for you to make this change on the version 5? Couldn't use version 6 due to php requirements :/

**Comment by jamesggordon** [comment] 2018-06-29 06:03
@PierreRambaud Sorry for taking so long to respond. I'm not sure it would be a good idea to merge this change into the 5.x branch because it relaxes a very important validation rule that a lot of old applications might be relying on.

However, I can offer two alternative methods for including the change in your project:

1. Fork 5.x, make the change again on a new branch, add your repo to the "repositories" section of your composer.json file and then change the reference to swiftmailer to be         `"swiftmailer/swiftmailer": "dev-your-branch-name"`. As long as you get all the references right, composer will magically pull in your branch instead of the 5.x branch from the swiftmailer repo.

2. Manually patch the two files using the following commands (and related patch files):

`patch -N -r ignore.rej vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Grammar.php < swift1.patch`
`patch -N -r ignore.rej vendor/swiftmailer/swiftmailer/lib/classes/Swift/Mime/Headers/MailboxHeader.php < swift2.patch`

swift1.patch:

    -84c84
    -<         self::$_grammar['atext'] = '[a-zA-Z0-9!#\$%&\'\*\+\-\/=\?\^_`\{\}\|~]';
    ----
    ->         self::$_grammar['atext'] = '[a-zA-Z0-9!#\$%&\'\*\+\-\/=\?\^_`\{\}\|~\\p{L}]';

swift2.patch:

    -343c343
    -<         if (!preg_match('/^'.$this->getGrammar()->getDefinition('addr-spec').'$/D',
    ----
    ->         if (!preg_match('/^'.$this->getGrammar()->getDefinition('addr-spec').'$/Du',

Before I switched to SwiftMailer 6 I used the second option and added those two commands to the scripts section of my composer.json file. I set things up so that they would be run automatically every time I ran composer install.

I hope that helps.

**Comment by KKSzymanowski** [comment] 2018-11-26 08:55
Hello.

I have a similar problem with Swiftmailer 6.1.2:
```
Method Swift_Mime_SimpleHeaderSet::__toString() must not throw an exception, 
caught Swift_AddressEncoderException: Non-ASCII characters not supported in local-part
```
I have the `ł` character in the e-mail address which is perfectly acceptable when sending emails via any client like Gmail or Outlook.

**Comment by KKSzymanowski** [comment] 2018-11-26 14:09
Furthermore, addresses which contain UTF-8 characters in the local part pass the `Egulias\EmailValidator\Validation\RFCValidation::isValid()` check used by Swiftmailer.

**Comment by c960657** [comment] 2018-11-26 14:57
@KKSzymanowski You need to use `Swift_AddressEncoder_Utf8AddressEncoder` and `Swift_Transport_Esmtp_SmtpUtf8Handler`. See “_Internationalized Email Addresses_” on https://swiftmailer.symfony.com/docs/messages.html#setting-bcc-recipients.

**Comment by ndberg** [comment] 2019-04-01 14:43
Thanks @c960657 for the link. But if I use:
````
$utf8Encoder = new Swift_AddressEncoder_Utf8AddressEncoder();
$transport->setAddressEncoder($utf8Encoder);
````
after this code the $transport object is always null. Any thoughts about this?

**Comment by golonix** [comment] 2019-06-19 07:02
@KKSzymanowski I have the same issue with Swiftmailer (v6.2.1). 

`Swift_SmtpTransport` luckily gives the ability to set extension handlers and address encoder, however
```
$smtpUtf8 = new Swift_Transport_Esmtp_SmtpUtf8Handler();
$transport->setExtensionHandlers([$smtpUtf8]);
$utf8Encoder = new Swift_AddressEncoder_Utf8AddressEncoder();
$transport->setAddressEncoder($utf8Encoder);
```
solves issue only partially. 
There is a problem with `Swift_Mime_SimpleHeaderFactory` class. This class takes address encoder as the last argument in a constructor, and by default, it is `Swift_AddressEncoder_IdnAddressEncoder`. 

During `Swift_SmtpTransport` construction, Swiftmailer resolves dependencies (of its parent's class) out of the container, and the problem is with container configuration.
To fix this issue (in the most simple way) and allow non-ascii emails, you need to override some of the registered dependencies:
```
\Swift_DependencyContainer::getInstance()
    ->register('transport.smtp')
    ->asNewInstanceOf('Swift_Transport_EsmtpTransport')
    ->withDependencies([
        'transport.buffer',
        'transport.smtphandlers',
        'transport.eventdispatcher',
        'transport.localdomain',
        'address.utf8addressencoder', // this is changed
    ])

    ->register('transport.smtphandlers')
    ->asArray()
    ->withDependencies([
        'transport.authhandler',
        'transport.smtputf8handler', // this is added
    ])

    ->register('mime.headerfactory')
    ->asNewInstanceOf('Swift_Mime_SimpleHeaderFactory')
    ->withDependencies([
        'mime.qpheaderencoder',
        'mime.rfc2231encoder',
        'email.validator',
        'properties.charset',
        'address.utf8addressencoder', // this is changed
    ]);
```

@fabpot do you think it would be feasible to make that address encoder thing parametrized (via config, environment variable, whatever) and use that during dependencies registration? It would be developer's choice to use `idn` or `utf8` address encoder...
