### ISSUE TITLE
Swiftmailer 6.2.5 serialize for asyncSending doesn't work anymore

### ISSUE THREAD

**Issue by markusramsak** [swiftmailer/swiftmailer#1321] opened 2021-01-13 06:39 UTC
| Q                   | A
| ------------------- | -----
| Bug report?         | yes
| Feature request?    | no
| RFC?                | no
| How used?           | Standalone
| Swiftmailer version | 6.2.5
| PHP version         | 7.4.9

### Observed behaviour
after the Swiftmailer 6.2.5 update the PHP-function serialize cannot be used anymore the write the mail in a text file for sending later by unserialize the content of the text file.

### Expected behaviour
__sleep() und __wakeup() shouldn't `throw new \BadMethodCallException('Cannot serialize '.__CLASS__);`

### Solution
revert the change or suggest/implement another solution for serializing an email mit swiftmailer and send it later async (mail queue).

**Comment by jderusse** [comment] 2021-01-13 07:39
@markusramsak could you please tell us the name of the class that throw the exception?

**Comment by markusramsak** [comment] 2021-01-13 07:42
vendor/swiftmailer/swiftmailer/lib/classes/Swift/Transport/AbstractSmtpTransport.php
and
vendor/swiftmailer/swiftmailer/lib/classes/Swift/ByteStream/TemporaryFileByteStream.php

**Comment by jderusse** [comment] 2021-01-13 08:48
Hmm, I don't see why php is trying to serialize a class that belongs to the Transport, while it should only serialize the Message.

Same for `TemporaryFileByteStream` this class create a temporary file and delete it on `__destruct`, serializing it does not  make sens. 

Could you please provide me a reproducer?

**Comment by markusramsak** [comment] 2021-01-13 09:22
I serialize the whole mailer class with transport and message so I don't have to know anything when unserialize the Swiftmailer.

```
class ImdSwiftMail
{
    protected $_sender = 'default';
    protected $_config = [];
    protected $_transportConfig = [];
    protected $_layout = 'default';
    protected $_viewVars = [];
    protected $_client = 'localhost';
    protected array $_dkimConfig = [];
    protected ?Swift_Mailer $_mailer = null;
    protected ?Swift_Message $_message = null;
    protected array $_ignoreHeaders = [];

    /**
     * @param string $template Email template
     * @param string $subject Betreff
     * @param string|array $to Empfänger
     * @param array $params sender|viewVars|layout|client|cc|bcc
     *
     * @return \App\Mailer\ImdSwiftMail
     */
    public static function init(string $template, string $subject, $to, $params = [])
    {
        return new ImdSwiftMail($template, $subject, $to, $params);
    }

    public function __construct(string $template, string $subject, $to, $params = [])
    {
        TableRegistry::getTableLocator()->get('MailAccounts')->setMailConfig();

        $this->_sender = 'default';
        if (!empty($params['sender'])) {
            $this->_sender = $params['sender'];
        }
        $this->_config = Mailer::getConfig($this->_sender);
        $this->_transportConfig = TransportFactory::getConfig($this->_config['transport']);

        $this->_viewVars = [];
        if (!empty($params['viewVars'])) {
            $this->_viewVars = $params['viewVars'];
        }

        $this->_layout = 'default';
        if (!empty($params['layout'])) {
            $this->_layout = $params['layout'];
        }

        $this->_client = 'localhost';
        if (!IS_LOCAL) {
            if (isset($this->_transportConfig['client'])) {
                $this->_client = $this->_transportConfig['client'];
            } else {
                $httpHost = env('HTTP_HOST');
                if ($httpHost) {
                    [$this->_client] = explode(':', $httpHost);
                }
            }
        }

        $viewClass = 'App\View\AppView';
        $templateFolderPath = 'email' . DS;
        $helpers = ['Html', 'HtmlEmail'];

        $encryption = $this->_transportConfig['tls'] ? 'tls' : null;
        if (strpos($this->_transportConfig['host'], 'ssl://') === 0) {
            $encryption = 'ssl';
            $this->_transportConfig['host'] = substr($this->_transportConfig['host'], strlen('ssl://'));
        }

        $transport = (new Swift_SmtpTransport())
            ->setHost($this->_transportConfig['host'])
            ->setPort($this->_transportConfig['port'])
            ->setEncryption($encryption)
            ->setTimeout($this->_transportConfig['timeout'])
            ->setLocalDomain($this->_client)
            ->setUsername($this->_transportConfig['username'])
            ->setPassword($this->_transportConfig['password']);

        $viewBuilder = new ViewBuilder();
        $viewBuilder->setClassName($viewClass)
            ->setHelpers($helpers)
            ->setTemplate($template)
            ->setLayout($this->_layout)
            ->setLayoutPath($templateFolderPath . 'html')
            ->setTemplatePath($templateFolderPath . 'html');

        $view = $viewBuilder->build($this->_viewVars);

        $html = $view->render();
        $html = trimWhitespace(str_replace(["\r\n", "\r"], "\n", $html));

        $viewBuilder = new ViewBuilder();
        $viewBuilder->setClassName($viewClass)
            ->setHelpers($helpers)
            ->setTemplate($template)
            ->setLayout($this->_layout)
            ->setLayoutPath($templateFolderPath . 'text')
            ->setTemplatePath($templateFolderPath . 'text');

        $view = $viewBuilder->build($this->_viewVars);

        $plain = $view->render();
        $plain = trimWhitespace(str_replace(["\r\n", "\r"], "\n", $plain));

        $this->_mailer = new Swift_Mailer($transport);

        $this->_message = new Swift_Message();
        $this->_message
            ->setSubject($subject)
            ->setFrom($this->_config['from'])
            ->setTo($to)
            ->setBoundary('wowDAS-Mail-' . date('Y-m-d_H_i_s'))
            ->setBody($html, 'text/html')
            ->addPart($plain, 'text/plain');

        if (!empty($params['messageId'])) {
            $this->setMessageId($params['messageId']);
        }

        if (!empty($params['cc'])) {
            $this->setCc($params['cc']);
        }

        if (!empty($params['bcc'])) {
            $this->setBcc($params['bcc']);
        }

        $this->_ignoreHeaders = ['Subject', 'To', 'Content-Type'];

        if (!empty($params['headers'])) {
            foreach ($params['headers'] as $name => $value) {
                $this->addTextHeader($name, $value);
            }
        }

        if (isset($this->_config['headers'])) {
            foreach ($this->_config['headers'] as $name => $value) {
                if (empty($params['headers']) or !isset($params['headers'][$name])) {
                    // Header noch nicht hinzugefügt
                    $this->addTextHeader($name, $value);
                }
            }
        }

        if (!empty($params['requestReadReceipt'])) {
            $this->_message->setReadReceiptTo($this->_config['from']);
            $this->addTextHeader('X-Confirm-reading-to', key($this->_config['from']));
            $this->addTextHeader('Return-Receipt-To', key($this->_config['from']));
        }

        if (!empty($params['signMessage'])) {
            $this->sign();
        }
    }

    /**
     * @return $this
     * @throws \Swift_SwiftException
     */
    public function sign()
    {
        $domain = trimWhitespace(file_get_contents(PRIVATE_PATH . 'dkim' . DS . 'current' . DS . 'domain.txt'));
        $privateKey = trimWhitespace(file_get_contents(PRIVATE_PATH . 'dkim' . DS . 'current' . DS . 'private.key'));
        $selector = trimWhitespace(file_get_contents(PRIVATE_PATH . 'dkim' . DS . 'current' . DS . 'selector.txt'));

        $this->_dkimConfig = [
            'domain' => $domain,
            'privateKey' => $privateKey,
            'selector' => $selector,
        ];

        $signer = (new Swift_Signers_DKIMSigner($this->_dkimConfig['privateKey'], $this->_dkimConfig['domain'], $this->_dkimConfig['selector']))
            ->setHashAlgorithm('rsa-sha256')
            ->setBodyCanon('relaxed')
            ->setHeaderCanon('relaxed');

        foreach ($this->_ignoreHeaders as $ignoreHeader) {
            $signer->ignoreHeader($ignoreHeader);
        }

        $this->_message->attachSigner($signer);

        return $this;
    }

    public function sendAsync()
    {
        (new ImdSwiftMailQueue())->addMail($this);

        ImdConfig::callAsyncCronjob('process_mailqueue');
    }

    /**
     * @return int
     * @throws \Exception
     */
    public function send()
    {
        $failedRecipients = [];
        $sent = $this->_mailer->send($this->_message, $failedRecipients);
        if ($sent === 0) {
            imdLogDebug($failedRecipients);
            throw new Exception('E-Mail konnte nicht versendet werden.');
        }

        if (!empty($failedRecipients)) {
            imdLogDebug($failedRecipients);
            throw new Exception('E-Mail konnte nicht an alle erfolgreich versendet werden.');
        }

        return $sent;
    }
}
```

**Comment by jderusse** [comment] 2021-01-13 10:14
Thank you for the reproducer.

You have the issue because the class contains the Mailer (which contains the transport).
You should not serialize this instance, this is not needed (the class does not contains contextual information), but most of all: by serializing it, you'll have unexpected behavior (see the `TemporaryFileByteStream` that delete generated files on `__destruct`).

Instead, I recommend you injecting the Mailer in the service in charge of unserializing contextual data, and sending the Email.

IMHO the exception `\BadMethodCallException('Cannot serialize '.__CLASS__)` is legit here. You cannot/shouldnt serialize this class.

I'm voting for closing the issue. 

But if needed (we wan't to avoid the BC Break), I can provide a patch that trigger deprecation (without compromising the security)

**Comment by markusramsak** [comment] 2021-01-13 10:19
@jderusse I know that serializing the message only would work but this is a regression to the previous version where it is possible. I serialize the object and deserialize it some seconds or minutes later to send the mail via cronjob and not directly only for performance reasons.

**Comment by markusramsak** [comment] 2021-01-13 11:39
My updated mailer works now with the newest version:

```
namespace App\Mailer;

use Cake\Http\Exception\BadRequestException;
use Cake\Mailer\Mailer;
use Cake\Mailer\TransportFactory;
use Cake\ORM\TableRegistry;
use Cake\View\ViewBuilder;
use Exception;
use Swift_Attachment;
use Swift_Mailer;
use Swift_Message;
use Swift_Signers_DKIMSigner;
use Swift_SmtpTransport;

class ImdSwiftMail
{
    protected string $_sender = 'default';
    protected array $_config = [];
    protected array $_transportConfig = [];
    protected string $_encryption = '';
    protected string $_layout = 'default';
    protected array $_viewVars = [];
    protected string $_client = 'localhost';
    protected array $_ignoreHeaders = [];
    protected ?Swift_Message $_message = null;

    /**
     * @param string $template Email template
     * @param string $subject Betreff
     * @param string|array $to Empfänger
     * @param array $params sender|viewVars|layout|client|cc|bcc
     *
     * @return \App\Mailer\ImdSwiftMail
     * @throws \Swift_RfcComplianceException
     * @throws \Swift_SwiftException
     */
    public static function init(string $template, string $subject, $to, array $params = []) : ImdSwiftMail
    {
        return new ImdSwiftMail($template, $subject, $to, $params);
    }

    /**
     * ImdSwiftMail constructor.
     *
     * @param string $template Email template
     * @param string $subject Betreff
     * @param string|array $to Empfänger
     * @param array $params sender|viewVars|layout|client|cc|bcc
     *
     * @throws \Swift_RfcComplianceException
     * @throws \Swift_SwiftException
     */
    public function __construct(string $template, string $subject, $to, array $params = [])
    {
        $this->_sender = 'default';
        if (!empty($params['sender'])) {
            $this->_sender = $params['sender'];
        }

        $config = Mailer::getConfig($this->_sender);
        if (!is_array($config)) {
            throw new BadRequestException('E-Mail-Konfiguration ' . $this->_sender . ' nicht gefunden.');
        }
        $this->_config = $config;

        $transportConfig = TransportFactory::getConfig($this->_config['transport']);

        $this->_transportConfig = $transportConfig;

        $this->_viewVars = [];
        if (!empty($params['viewVars'])) {
            $this->_viewVars = $params['viewVars'];
        }

        $this->_layout = 'default';
        if (!empty($params['layout'])) {
            $this->_layout = $params['layout'];
        }

        $this->_client = 'localhost';
        if (!IS_LOCAL) {
            if (isset($this->_transportConfig['client'])) {
                $this->_client = $this->_transportConfig['client'];
            } else {
                $httpHost = env('HTTP_HOST');
                if ($httpHost) {
                    [$this->_client] = explode(':', $httpHost);
                }
            }
        }

        $viewClass = 'App\View\AppView';
        $templateFolderPath = 'email' . DS;
        $helpers = ['Html', 'HtmlEmail'];

        $this->_encryption = $this->_transportConfig['tls'] ? 'tls' : '';
        if (strpos($this->_transportConfig['host'], 'ssl://') === 0) {
            $this->_encryption = 'ssl';
            $this->_transportConfig['host'] = substr($this->_transportConfig['host'], strlen('ssl://'));
        }

        $viewBuilder = new ViewBuilder();
        $viewBuilder->setClassName($viewClass)
            ->setHelpers($helpers)
            ->setTemplate($template)
            ->setLayout($this->_layout)
            ->setLayoutPath($templateFolderPath . 'html')
            ->setTemplatePath($templateFolderPath . 'html');

        $view = $viewBuilder->build($this->_viewVars);

        $html = $view->render();
        $html = trimWhitespace(str_replace(["\r\n", "\r"], "\n", $html));

        $viewBuilder = new ViewBuilder();
        $viewBuilder->setClassName($viewClass)
            ->setHelpers($helpers)
            ->setTemplate($template)
            ->setLayout($this->_layout)
            ->setLayoutPath($templateFolderPath . 'text')
            ->setTemplatePath($templateFolderPath . 'text');

        $view = $viewBuilder->build($this->_viewVars);

        $plain = $view->render();
        $plain = trimWhitespace(str_replace(["\r\n", "\r"], "\n", $plain));

        $this->_message = new Swift_Message();
        $this->_message
            ->setSubject($subject)
            ->setFrom($this->_config['from'])
            ->setTo($to)
            ->setBoundary('Mail-' . date('Y-m-d_H_i_s'))
            ->setBody($html, 'text/html')
            ->addPart($plain, 'text/plain');

        if (!empty($params['messageId'])) {
            $this->setMessageId($params['messageId']);
        }

        if (!empty($params['cc'])) {
            $this->setCc($params['cc']);
        }

        if (!empty($params['bcc'])) {
            $this->setBcc($params['bcc']);
        }

        $this->_ignoreHeaders = ['Subject', 'To', 'Content-Type'];

        if (!empty($params['headers'])) {
            foreach ($params['headers'] as $name => $value) {
                $this->addTextHeader($name, $value);
            }
        }

        if (isset($this->_config['headers'])) {
            foreach ($this->_config['headers'] as $name => $value) {
                if (empty($params['headers']) or !isset($params['headers'][$name])) {
                    // Header noch nicht hinzugefügt
                    $this->addTextHeader($name, $value);
                }
            }
        }
    }

    public function sendAsync() : void
    {
        (new ImdSwiftMailQueue())->addMail($this);

        callAsyncCronjob('process_mailqueue');
    }

    /**
     * @return int
     * @throws \Exception
     */
    public function send() : int
    {
        $failedRecipients = [];

        $transport = (new Swift_SmtpTransport())
            ->setHost($this->_transportConfig['host'])
            ->setPort($this->_transportConfig['port'])
            ->setEncryption($this->_encryption)
            ->setTimeout($this->_transportConfig['timeout'])
            ->setLocalDomain($this->_client)
            ->setUsername($this->_transportConfig['username'])
            ->setPassword($this->_transportConfig['password']);

        $mailer = new Swift_Mailer($transport);
        $sent = $mailer->send($this->_message, $failedRecipients);
        
        return $sent;
    }
}
```

**Closed** 2021-01-13 11:59 UTC
