### ISSUE TITLE
Exception messages from _doRcptToCommand should not be discarded

### ISSUE THREAD

**Issue by kdrobec** [swiftmailer/swiftmailer#164] opened 2012-02-15 12:10 UTC
AbstractSmtpTransport::_doMailTransaction catches instances of Swift_TransportException yielded by calls to _doRcptToCommand and handles them by only listing a failed recipient while simultaneously discarding the exception message.

This hides information the mail server is trying to convey about the reasons for rejecting a recipient. This makes debugging harder and hinders informative error reporting.

A possible solution would be to either change the filling of $failedRecipients (which could break legacy client code) or extend the interface definition by (a) an additional feedback array or (b) an optional flag to select an "extended" format for $failedRecipients.

**Comment by michaelhogg** [comment] 2015-01-23 15:49
Probably a duplicate of #353 and #424

**Closed** 2021-11-17 07:10 UTC
