### ISSUE TITLE
Encoding issue with subject & Base64HeaderEncoder

### ISSUE THREAD

**Issue by Bacteries** [swiftmailer/swiftmailer#869] opened 2017-02-01 16:48 UTC
Hi,
I have encounter delivery issues with Swiftmail & Mandrill.
I had to dig to understand the issue : 
Subject is encoded in UTF-8 and special character doesn't break the right way : 

Here an example, using \Swift_Mime_HeaderEncoder_Base64HeaderEncoder : 
`Subject: Information importante : votre CV n'est plus =?UTF-8?B?ZGlmZnVzw?=
 =?UTF-8?B?6k=?= sur le domaine e.cambray.info`

This fail, the format works (I don't specify encoder for header) : 
`Subject: Information importante : votre CV n'est plus =?UTF-8?Q?diff?=
 =?UTF-8?Q?us=C3=A9?= sur le domaine e.cambray.info
`

But we already have enconding issue that force us to use Swift_Mime_HeaderEncoder_Base64HeaderEncoder...

I don't know enough on SMTP protocol. So it is a bug or a do I misundersstand something ?

Thanks!

**Comment by borkor** [comment] 2017-05-11 08:29
I guess there are no multiple issues with subject encoder. For example I have issues with this subject:

Original 
`Vaš kolega je naručio oglas`

Encoded
`Subject: =?utf-8?Q?Va=C5=A1?= kolega je =?utf-8?Q?naru=C4=8Dio?= oglas`

Viewable subject in YahooMail
`Vašnaručiooglas`

**Comment by Rotzbua** [comment] 2017-05-11 11:04
Seems to be a duplicate of #665

**Closed** 2021-11-17 07:10 UTC
